### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by vvaths** [InfoMSandbox/real-brightside#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by vyas000** [comment]
hi

**Comment by 05caniffa** [comment]
hey

**Comment by bkenn** [comment]
comment here

**Comment by bsnyder74** [comment]
hello

**Comment by weesooo** [comment]
Hey

**Comment by mattmbrightside** [comment]
test hi whatever I like

**Comment by AchyuthaBharadwaj** [comment]
hi

**Comment by nshuttle** [comment]
Hi - Thank you for helping today

**Comment by CRSTUMP** [comment]
hi

**Comment by harisiddarthvk** [comment]
test

**Comment by kwilsbach-gb** [comment]
comment

**Comment by BrandonGrayBrightside** [comment]
Yo

**Comment by alan-leeson-brightside** [comment]
Look, no hands!

**Comment by rsampath19** [comment]
hi
